name: ci-speed
author: thedumbterminal
description: Interact with CI-Speed
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Upload
      run: upload_to_ci_speed.sh
      shell: bash
