"""Projects unique per user

Revision ID: 04b2aa22059f
Revises: e33c1dca09c2
Create Date: 2022-05-21 19:16:08.072573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "04b2aa22059f"
down_revision = "e33c1dca09c2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uniq_user_id_project", "project", ["user_id", "name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uniq_user_id_project", "project", type_="unique")
    # ### end Alembic commands ###
