"""Support skipped tests

Revision ID: 0cefa788c21d
Revises: bfdf8655992e
Create Date: 2022-06-23 21:02:43.906219

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0cefa788c21d"
down_revision = "bfdf8655992e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skipped_test",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("test_case_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["test_case_id"],
            ["test_case.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("skipped_test")
    # ### end Alembic commands ###
