"""Add build commit SHA

Revision ID: 31f8ec031c8f
Revises: 7b0387ce1635
Create Date: 2022-12-16 00:26:50.308173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f8ec031c8f'
down_revision = '7b0387ce1635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commit_sha', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build', schema=None) as batch_op:
        batch_op.drop_column('commit_sha')

    # ### end Alembic commands ###
