"""add cascade project fk to users_projects

Revision ID: 4dfa97c59993
Revises: e052f36c32e2
Create Date: 2024-10-21 10:14:03.883226

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "4dfa97c59993"
down_revision = "e052f36c32e2"
branch_labels = None
depends_on = None


def upgrade():
    op.drop_constraint(
        "users_projects_project_id_fkey", "users_projects", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "users_projects",
        "project",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
        onupdate="CASCADE",
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_projects_project_id_fkey", "build", type_="foreignkey")
    op.create_foreign_key(None, "users_projects", "project", ["project_id"], ["id"])

    # ### end Alembic commands ###
