"""Add waypoints

Revision ID: 5170a027a888
Revises: 2b0de42ea2ad
Create Date: 2024-08-11 16:04:01.151034

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5170a027a888"
down_revision = "2b0de42ea2ad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "waypoint",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["build_id"], ["build.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("build_id", "name", name="build_id_name"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("waypoint")
    # ### end Alembic commands ###
