"""not null fks

Revision ID: 7b0387ce1635
Revises: 0cefa788c21d
Create Date: 2022-06-23 21:06:16.054353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b0387ce1635'
down_revision = '0cefa788c21d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_case', 'test_suite_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_failure', 'test_case_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('skipped_tests', 'test_case_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_suite', 'test_run_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_suite', 'test_run_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('skipped_tets', 'test_case_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_failure', 'test_case_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_case', 'test_suite_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
