"""cascade project fk on builds

Revision ID: e052f36c32e2
Revises: 5170a027a888
Create Date: 2024-10-06 18:21:02.825887

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "e052f36c32e2"
down_revision = "5170a027a888"
branch_labels = None
depends_on = None


def upgrade():
    op.drop_constraint("build_project_id_fkey", "build", type_="foreignkey")
    op.create_foreign_key(
        None,
        "build",
        "project",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
        onupdate="CASCADE",
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("build_project_id_fkey", "build", type_="foreignkey")
    op.create_foreign_key(None, "build", "project", ["project_id"], ["id"])

    # ### end Alembic commands ###
