"""Adding reference to builds

Revision ID: f4a1d9c33387
Revises: ad19c9990883
Create Date: 2022-05-18 09:06:48.002608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f4a1d9c33387"
down_revision = "ad19c9990883"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("build", sa.Column("ref", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("build", "ref")
    # ### end Alembic commands ###
