# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.4"
        cache: 'pip'
    - name: Install dependencies
      run: |
        scripts/install.sh
    - name: CI
      run: |
        invoke ci
    - name: Use local ci-speed-action
      if: success() || failure()
      uses: thedumbterminal/ci-speed-github-action@main
      with:
        token: ${{ secrets.CI_SPEED_AUTH_TOKEN }}
        results: test_results.xml

  automerge:
    needs: build
    runs-on: ubuntu-latest

    # For auto merging
    permissions:
      pull-requests: write
      contents: write

    steps:
    - uses: actions/checkout@v3
    - uses: fastify/github-action-merge-dependabot@v3
